  server:
    servlet:
      context-path: /invoice-service
      port: 8080
      compression:
        mime-types:
          - application/json

  spring:
    application:
      name: invoice-service
    main:
      allow-bean-definition-overriding: true
    datasource:
      url: jdbc:postgresql://isabelle.db.elephantsql.com/htzuglca
      username: htzuglca
      password: nWxWR2W9Zz1yRWwglQkjCicVtuFpLkUc
      driverClassName: org.postgresql.Driver
      hikari:
        maximum-pool-size: 2

    # JPA
    jpa:
      open-in-view: false
      show-sql: true
      format-sql: true
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      properties:
        hibernate:
          jdbc:
            batch_size: 50
    sql:
      init:
        continue-on-error: true

    ## Enable liquidbase
    liquibase:
      enabled: true
      change-log: classpath:db/changelog/changelog-local.xml

  microsservice:
    package:
      url: http://localhost:8080/package

  ## Enabling rabbitmq

  #  rabbitmq:
  #    host: 127.0.0.1
  #    port: 5672
  #    username: <username>
  #    password: <password>
  #    cache:
  #      connection:
  #        mode: CONNECTION
  #      channel:
  #        size: 50
  #      checkout-timeout: 10000